import { writeFileSync, readFileSync, existsSync, copyFileSync } from 'fs';
import { join } from 'path';
import { randomBytes } from 'crypto';

const ROOT_DIR = process.cwd();

/**
 * Ensure .env exists. If not, create from .env.example (or minimal template).
 */
export function ensureEnvExists() {
  const envPath = join(ROOT_DIR, '.env');
  const examplePath = join(ROOT_DIR, '.env.example');

  if (existsSync(envPath)) return envPath;

  if (existsSync(examplePath)) {
    copyFileSync(examplePath, envPath);
    return envPath;
  }

  // Minimal template
  const minimal = `# Harbinger Configuration
# Generated by setup wizard — never edit manually unless needed

AUTH_SECRET=${randomBytes(32).toString('base64')}
AUTH_TRUST_HOST=true
APP_URL=
APP_HOSTNAME=
GH_TOKEN=
GH_OWNER=
GH_REPO=
TELEGRAM_BOT_TOKEN=
TELEGRAM_WEBHOOK_SECRET=
TELEGRAM_VERIFICATION=
TELEGRAM_CHAT_ID=
GH_WEBHOOK_SECRET=
ANTHROPIC_API_KEY=
OPENAI_API_KEY=
GITHUB_CLIENT_ID=
GITHUB_CLIENT_SECRET=
APP_NAME=Harbinger
APP_ENV=development
APP_PORT=8080
DB_NAME=harbinger
DB_USER=harbinger
DB_PASSWORD=change-me-in-production
JWT_SECRET=change-me-in-production
NEO4J_PASSWORD=neo4j-change-me
HEXSTRIKE_URL=http://localhost:3001
PENTAGI_URL=http://localhost:3002
MCP_UI_URL=http://localhost:3003
REDTEAM_URL=http://localhost:3004
FRONTEND_PORT=3000
DOCKER_SOCKET=/var/run/docker.sock
`;
  writeFileSync(envPath, minimal);
  return envPath;
}

/**
 * Set or update a variable in .env. Creates file if missing.
 */
export function setEnvVariable(key, value) {
  ensureEnvExists();
  const envPath = join(ROOT_DIR, '.env');
  let content = readFileSync(envPath, 'utf-8');
  const regex = new RegExp(`^${key}=.*$`, 'm');

  if (regex.test(content)) {
    content = content.replace(regex, `${key}=${value}`);
  } else {
    content = content.trimEnd() + `\n${key}=${value}\n`;
  }

  writeFileSync(envPath, content);
  return envPath;
}

/**
 * Set multiple variables at once.
 */
export function setEnvVariables(updates) {
  ensureEnvExists();
  const envPath = join(ROOT_DIR, '.env');
  let content = readFileSync(envPath, 'utf-8');

  for (const [key, value] of Object.entries(updates)) {
    const regex = new RegExp(`^${key}=.*$`, 'm');
    if (regex.test(content)) {
      content = content.replace(regex, `${key}=${value}`);
    } else {
      content = content.trimEnd() + `\n${key}=${value}\n`;
    }
  }

  writeFileSync(envPath, content);
  return envPath;
}

/**
 * Write frontend/.env with VITE_* vars derived from platform config.
 * apiUrl empty = use Vite proxy (relative URLs) for local dev.
 */
export function writeFrontendEnv({ apiUrl = '', wsUrl, mcpUrl }) {
  const frontendEnvPath = join(ROOT_DIR, 'frontend', '.env');
  const ws = wsUrl || 'ws://localhost:8080/ws';
  const mcp = mcpUrl || 'http://localhost:3001';

  const content = `# Auto-generated by setup wizard — do not edit manually
VITE_API_URL=${apiUrl}
VITE_WS_URL=${ws}
VITE_MCP_URL=${mcp}
`;
  writeFileSync(frontendEnvPath, content);
  return frontendEnvPath;
}
