#!/usr/bin/env bash
# Format a finding into a bug bounty submission report
# Usage: ./submit-report.sh <finding-file> [output-dir]
set -euo pipefail
FINDING="${1:?Usage: submit-report.sh <finding-file> [output-dir]}"
OUTDIR="${2:-${HARBINGER_WORKSPACE:-$HOME/.harbinger/workspace}/reports}"
mkdir -p "$OUTDIR"

if [ ! -f "$FINDING" ]; then
  echo "[!] Finding file not found: $FINDING"
  exit 1
fi

TIMESTAMP=$(date +%Y%m%d-%H%M%S)
REPORT="$OUTDIR/report-$TIMESTAMP.md"

echo "[*] Generating report from $FINDING"

# Extract key fields from finding (expects JSON or structured text)
if command -v jq &>/dev/null && jq empty "$FINDING" 2>/dev/null; then
  TITLE=$(jq -r '.title // "Untitled Finding"' "$FINDING")
  SEVERITY=$(jq -r '.severity // "medium"' "$FINDING")
  TARGET=$(jq -r '.target // "unknown"' "$FINDING")
  DESCRIPTION=$(jq -r '.description // ""' "$FINDING")
  STEPS=$(jq -r '.steps // ""' "$FINDING")
  IMPACT=$(jq -r '.impact // ""' "$FINDING")
  EVIDENCE=$(jq -r '.evidence // ""' "$FINDING")
else
  TITLE="Finding Report — $TIMESTAMP"
  SEVERITY="medium"
  TARGET="See attached"
  DESCRIPTION=$(cat "$FINDING")
  STEPS=""
  IMPACT=""
  EVIDENCE=""
fi

cat > "$REPORT" <<REPORT
# $TITLE

**Severity:** $SEVERITY
**Target:** $TARGET
**Date:** $(date -u +%Y-%m-%dT%H:%M:%SZ)
**Reporter:** Harbinger Security Platform

## Summary

$DESCRIPTION

## Steps to Reproduce

${STEPS:-"1. Navigate to the target URL
2. [Provide detailed reproduction steps]
3. Observe the vulnerability"}

## Impact

${IMPACT:-"[Describe the security impact and potential for exploitation]"}

## Evidence

${EVIDENCE:-"[Attach screenshots, HTTP requests/responses, and proof-of-concept]"}

## Remediation

[Suggested fix based on the vulnerability class]

---
*Generated by Harbinger — Autonomous Security Platform*
REPORT

echo "[+] Report generated: $REPORT"
echo "[*] Review and edit before submission"
wc -l "$REPORT" | awk '{print "[*] " $1 " lines"}'
