// Export all API modules
export { apiClient } from './client'
export { providersApi } from './providers'
export { agentsApi } from './agents'
export { chatApi } from './chat'
export { dockerApi } from './docker'
export { browserApi } from './browser'
export { mcpApi } from './mcp'
export { workflowsApi } from './workflows'
export { dashboardApi } from './dashboard'
export { autonomousApi } from './autonomous'
export { skillsApi } from './skills'
export { c2Api } from './c2'
export { lolApi } from './lol'

// Re-export types
export type { ModelInfo, ProviderInfo, ProviderTestResult } from './providers'
export type { CreateAgentRequest, AgentResponse } from './agents'
export type { ChatMessage, ChatSession, SendMessageRequest } from './chat'
export type { CreateContainerRequest, ContainerStats } from './docker'
export type { CreateBrowserRequest, BrowserScreenshot, BrowserElement } from './browser'
export type { CreateMCPRequest, MCPTool, MCPResource, MCPPrompt } from './mcp'
export type { CreateWorkflowRequest, WorkflowExecution } from './workflows'
export type { ActivityItem, SystemStats, ServiceHealth } from './dashboard'
export type { AgentThought, SwarmState, AutonomousStats, EfficiencyScore } from './autonomous'
export type { SkillCategory, Skill, SkillParameter, SkillExecutionResult } from './skills'
export type { C2Framework, C2Listener, C2Payload, C2Implant, C2Task, C2Operation, C2AttackChain, C2AttackStep, C2Dashboard, C2SearchResult } from './c2'
export type { LOLProject, LOLEntry, LOLCommand, LOLDetection, LOLChain, LOLChainStep, LOLStats } from './lol'
